/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.82
 * Generated at: 2023-02-02 08:56:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class reg_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");

	String path = request.getContextPath();

      out.write("\r\n");
      out.write("<link href=\"");
      out.print(path );
      out.write("/css/index.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.print(path );
      out.write("/css/reg.css\" rel=\"stylesheet\">\r\n");
      out.write("<script>\r\n");
      out.write("function save(){\r\n");
      out.write("	let frm = document.frm;\r\n");
      out.write("	let s_id = frm.s_id;\r\n");
      out.write("	let s_name = frm.s_name;\r\n");
      out.write("	let t_id = frm.t_id;\r\n");
      out.write("	let s_grade = frm.s_grade;\r\n");
      out.write("	let weekday = frm.weekday;\r\n");
      out.write("	let start_h = frm.start_h;\r\n");
      out.write("	let end_h = frm.end_h;\r\n");
      out.write("	\r\n");
      out.write("	if(s_id == \"\"){\r\n");
      out.write("		alert(\"과목 입력하세요\");\r\n");
      out.write("		s_id.focus();\r\n");
      out.write("	}else{\r\n");
      out.write("		frm.submit();\r\n");
      out.write("		alert(\"등록완료\");\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("		<h1>연습</h1>\r\n");
      out.write("	</header>\r\n");
      out.write("	<nav>\r\n");
      out.write("		<ol>\r\n");
      out.write("			<li><a href=\"");
      out.print(path );
      out.write("/list\">조회</a></li>\r\n");
      out.write("			<li><a href=\"");
      out.print(path );
      out.write("/reg\">등록</a></li>\r\n");
      out.write("		</ol>\r\n");
      out.write("	</nav>\r\n");
      out.write("	<section>\r\n");
      out.write("	<form name=\"frm\" method=\"post\" action=\"reg\">\r\n");
      out.write("		<table>\r\n");
      out.write("			<caption>수강과목 등록</caption>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td class=\"main\">교과목 코드</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"s_id\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td class=\"main\">교과명</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"s_name\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td class=\"main\">담당강사</td>\r\n");
      out.write("				<td>\r\n");
      out.write("					<select name=\"t_id\">\r\n");
      out.write("						<option value=\"\">선택</option>\r\n");
      out.write("						<option value=\"1\">정국교수</option>\r\n");
      out.write("						<option value=\"2\">뷔교수</option>\r\n");
      out.write("						<option value=\"3\">지민교수</option>\r\n");
      out.write("						<option value=\"4\">제이홉교수</option>\r\n");
      out.write("						<option value=\"5\">슈가교수</option>\r\n");
      out.write("						<option value=\"6\">진교수</option>\r\n");
      out.write("						<option value=\"7\">RM교수</option>\r\n");
      out.write("					</select>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td class=\"main\">학점</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"s_grade\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td class=\"main\">요일</td>\r\n");
      out.write("				<td>\r\n");
      out.write("					<input type=\"radio\" name=\"weekday\" value=\"M\">월\r\n");
      out.write("					<input type=\"radio\" name=\"weekday\" value=\"TU\">화\r\n");
      out.write("					<input type=\"radio\" name=\"weekday\" value=\"W\">수\r\n");
      out.write("					<input type=\"radio\" name=\"weekday\" value=\"TH\">목\r\n");
      out.write("					<input type=\"radio\" name=\"weekday\" value=\"F\">금\r\n");
      out.write("					<input type=\"radio\" name=\"weekday\" value=\"S\">토\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td class=\"main\">수업시작시간</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"start_h\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td class=\"main\">수업종료시간</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"end_h\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td class=\"main\" colspan=\"2\">\r\n");
      out.write("					<input type=\"button\" value=\"목록\" onclick=\"window.location='");
      out.print(path);
      out.write("/list'\">\r\n");
      out.write("					<input type=\"button\" value=\"저장\" onclick=\"save()\">\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("	</form>\r\n");
      out.write("	</section>\r\n");
      out.write("	<footer>\r\n");
      out.write("		hi\r\n");
      out.write("	</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
